package routers

import (
	"golang-webservice/controllers"

	"github.com/gin-gonic/gin"

	_ "golang-webservice/docs" // docs is generated by Swag CLI, you have to import it.

	ginSwagger "github.com/swaggo/gin-swagger"

	swaggerfiles "github.com/swaggo/files"
)

// @title Book API
// @version 1.0
// @description This is a simple service for managing books
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email soberkoder@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host 127.0.0.1:8080
// @BasePath /
func StartServer() *gin.Engine {
	router := gin.Default()

	// Read All Books
	router.GET("/books", controllers.GetBooks)

	// Post A Book
	router.POST("/books", controllers.CreateBook)

	// Update A Book
	router.PUT("/books/:bookID", controllers.UpdateBook)

	// Read A Book
	router.GET("/books/:bookID", controllers.GetBook)

	// Delete A Book
	router.DELETE("/books/:bookID", controllers.DeleteBook)

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	return router
}
